CREATE DATABASE QLHANG
GO
USE QLHANG
GO

CREATE TABLE VATTU(
    MAVT varchar(10) PRIMARY KEY, 
    TENVT nvarchar(50),
    DVTINH nvarchar(50),
    SLCON INT
);

CREATE TABLE HDBAN(
    MAHD varchar(10) PRIMARY KEY, 
    NGAYXUAT DATE,
    HOTENKHACH nvarchar(50)
);

CREATE TABLE HANGXUAT(
    MAHD varchar(10),
    MAVT varchar(10),
    DONGIA INT,
    SLBAN INT,
    CONSTRAINT HANGXUAT_PK PRIMARY KEY (MAHD, MAVT)
);

ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_HDBAN
FOREIGN KEY (MAHD) REFERENCES HDBAN (MAHD);
ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_VATTU
FOREIGN KEY (MAVT) REFERENCES VATTU (MAVT);

INSERT INTO VATTU VALUES
('VT03', 'GACH', 'VIEN', 200000),
('VT04', 'XI-MANG', 'BAO', 4000);

INSERT INTO HDBAN VALUES
('HD03', '2022-10-05', 'LÊ QUYNH ANH'),
('HD04', '2022-09-27', 'HOANG THI HOA');

INSERT INTO HANGXUAT VALUES
('HD03', 'VT03', 8000, 600),
('HD03', 'VT04', 46000, 40),
('HD04', 'VT03', 8300, 200),
('HD04', 'VT04', 49000, 50);


